/**
 * CityPay POS API
 * CityPay Point of Sale API for payment with card present devices including EMV readers and contactless POS readers.  The API makes it simple to add EMV and contactless card acceptance to iOS, Android, Tablet and desktop applicaitons using a HTTPS protocol. It segregates the complexity of payment processing from the sales environment and eliminates any necessity for the target system to handle card data. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DeviceInfo {
    /**
     * The name of the device
     */
    name?: string;
    /**
     * The serial number of the device
     */
    serialno?: string;
    /**
     * Whether the device is portable
     */
    portable?: boolean;
    /**
     * Whether the device is busy or available for a transaction
     */
    busy?: boolean;
    /**
     * Whether the device is currently charging
     */
    batteryCharging?: boolean;
    /**
     * A percentage value of the battery
     */
    batteryPercentage?: number;
    /**
     * Whether the device has a printer
     */
    printer?: boolean;
}
